CREATE TABLE [dbo].[Affaire] (

	[Code affaire] varchar(255) NULL, 
	[Affaire] varchar(255) NULL, 
	[Code entreprise] int NULL, 
	[Code dossier] int NULL, 
	[Code client] varchar(255) NULL, 
	[Date création] date NULL, 
	[Date modification] date NULL, 
	[Date affaire] date NULL, 
	[Date accord] date NULL, 
	[Date signature] date NULL, 
	[Date premier devis] date NULL, 
	[Code salarié commercial] varchar(255) NULL, 
	[Code salarié technicien] varchar(255) NULL, 
	[Code situation dossier] varchar(255) NULL, 
	[Situation dossier] varchar(255) NULL, 
	[Code priorité traitement] int NULL, 
	[Priorité traitement] varchar(255) NULL, 
	[Code origine] varchar(255) NULL, 
	[Origine] varchar(255) NULL, 
	[Code type] varchar(255) NULL, 
	[Type] varchar(255) NULL, 
	[Code produit] varchar(255) NULL, 
	[Produit] varchar(255) NULL, 
	[CA prévu] float NULL, 
	[Taux de réussite] float NULL, 
	[Critère libre 1] varchar(255) NULL, 
	[Critère libre 2] varchar(255) NULL, 
	[Critère libre 3] varchar(255) NULL, 
	[Critère libre 4] varchar(255) NULL, 
	[Critère libre 5] varchar(255) NULL, 
	[Critère libre 6] varchar(255) NULL, 
	[Critère libre 7] varchar(255) NULL, 
	[Critère libre 8] varchar(255) NULL, 
	[Critère libre 9] varchar(255) NULL, 
	[Critère libre 10] varchar(255) NULL, 
	[Critère libre 11] varchar(255) NULL, 
	[Critère libre 12] varchar(255) NULL, 
	[Critère libre 13] varchar(255) NULL, 
	[Critère libre 14] varchar(255) NULL, 
	[Critère libre 15] varchar(255) NULL, 
	[Critère libre 16] varchar(255) NULL, 
	[Critère libre 17] varchar(255) NULL, 
	[Critère libre 18] varchar(255) NULL, 
	[Critère libre 19] varchar(255) NULL, 
	[Critère libre 20] varchar(255) NULL, 
	[Critère libre 21] varchar(255) NULL, 
	[Critère libre 22] varchar(255) NULL, 
	[Critère libre 23] varchar(255) NULL, 
	[Critère libre 24] varchar(255) NULL, 
	[Critère libre 25] varchar(255) NULL, 
	[Critère libre 26] varchar(255) NULL, 
	[Critère libre 27] varchar(255) NULL, 
	[Critère libre 28] varchar(255) NULL, 
	[Critère libre 29] varchar(255) NULL, 
	[Critère libre 30] varchar(255) NULL, 
	[Critère libre 31] varchar(255) NULL, 
	[Critère libre 32] varchar(255) NULL, 
	[Critère libre 33] varchar(255) NULL, 
	[Critère libre 34] varchar(255) NULL, 
	[Critère libre 35] varchar(255) NULL, 
	[Critère libre 36] varchar(255) NULL, 
	[Critère libre 37] varchar(255) NULL, 
	[Critère libre 38] varchar(255) NULL, 
	[Critère libre 39] varchar(255) NULL, 
	[Critère libre 40] varchar(255) NULL, 
	[IdAffaire] varchar(255) NOT NULL
);