CREATE TABLE [dbo].[Article] (

	[Code article] varchar(255) NULL, 
	[Article] varchar(255) NULL, 
	[Type article] varchar(255) NULL, 
	[Code famille 1] varchar(255) NULL, 
	[Famille 1] varchar(255) NULL, 
	[Code famille 2] varchar(255) NULL, 
	[Famille 2] varchar(255) NULL, 
	[Code famille 3] varchar(255) NULL, 
	[Famille 3] varchar(255) NULL, 
	[Code famille 4] varchar(255) NULL, 
	[Famille 4] varchar(255) NULL, 
	[Code poste gestion achat] varchar(255) NULL, 
	[Code poste gestion vente] varchar(255) NULL, 
	[Mode lancement/réappro] varchar(255) NULL, 
	[Mode post-conso] varchar(255) NULL, 
	[Classement ABC] varchar(255) NULL, 
	[Délai d'appro] int NULL, 
	[Quantité économique lot] float NULL, 
	[Est géré en stock] varchar(255) NULL, 
	[Mode réservation stock] varchar(255) NULL, 
	[Niveau stock sécurité] float NULL, 
	[Niveau stock alerte] float NULL, 
	[Niveau stock maxi] float NULL, 
	[Dernier prix achat] float NULL, 
	[Prix exploitation] float NULL, 
	[Unité exploitation] varchar(255) NULL, 
	[Date création] date NULL, 
	[Date modification] date NULL, 
	[IdArticle] varchar(255) NOT NULL
);