CREATE TABLE [dbo].[Calendrier] (

	[Date] date NULL, 
	[Année] int NULL, 
	[Année exercice] int NULL, 
	[N° mois] varchar(2) NULL, 
	[N° mois exercice] int NULL, 
	[Mois] varchar(20) NULL, 
	[Mois exercice] varchar(20) NULL, 
	[Année - Mois] varchar(30) NULL, 
	[Période] varchar(6) NULL, 
	[N° jour relatif] int NULL, 
	[N° mois relatif] int NULL, 
	[N° trimestre relatif] int NULL, 
	[N° année relatif] int NULL, 
	[Jour relatif] varchar(20) NULL, 
	[Mois relatif] varchar(20) NULL, 
	[Trimestre relatif] varchar(20) NULL, 
	[Année relatif] varchar(20) NULL, 
	[Jour] varchar(20) NULL, 
	[N° jour] int NULL, 
	[N° jour du mois] int NULL, 
	[Trimestre] varchar(20) NULL, 
	[Semaine] varchar(20) NULL, 
	[Est ouvrable] bit NULL, 
	[Est férié] bit NULL, 
	[Jour férié] varchar(30) NULL, 
	[Mois fiscal] varchar(20) NULL, 
	[N° mois fiscal] int NULL, 
	[Année fiscale] int NULL
);