CREATE TABLE [dbo].[Client] (

	[Code client] varchar(255) NULL, 
	[Client] varchar(255) NULL, 
	[Code entreprise] int NULL, 
	[Code origine] varchar(255) NULL, 
	[Origine] varchar(255) NULL, 
	[Code groupe client] int NULL, 
	[Code NAF] varchar(255) NULL, 
	[NAF] varchar(255) NULL, 
	[Code métier] varchar(255) NULL, 
	[Métier] varchar(255) NULL, 
	[Code profession] varchar(255) NULL, 
	[Profession] varchar(255) NULL, 
	[Code type client] varchar(255) NULL, 
	[Type client] varchar(255) NULL, 
	[Code zone commerciale] varchar(255) NULL, 
	[Zone commerciale] varchar(255) NULL, 
	[Code secteur géographique] varchar(255) NULL, 
	[Secteur géographique] varchar(255) NULL, 
	[Qualité] varchar(255) NULL, 
	[Est client] varchar(255) NULL, 
	[Date création] date NULL, 
	[Date modification] date NULL, 
	[Adresse 1] varchar(255) NULL, 
	[Adresse 2] varchar(255) NULL, 
	[Code postal] varchar(255) NULL, 
	[Ville] varchar(255) NULL, 
	[Code département] varchar(255) NULL, 
	[Département] varchar(255) NULL, 
	[Région] varchar(255) NULL, 
	[Pays] varchar(255) NULL, 
	[Téléphone 1] varchar(255) NULL, 
	[Téléphone 2] varchar(255) NULL, 
	[Code mailing] varchar(255) NULL, 
	[Mailing] varchar(255) NULL, 
	[EMail] varchar(255) NULL, 
	[Civilité] varchar(255) NULL, 
	[GPS latitude] float NULL, 
	[GPS longitude] float NULL, 
	[Critère libre 1] varchar(255) NULL, 
	[Critère libre 2] varchar(255) NULL, 
	[Critère libre 3] varchar(255) NULL, 
	[Critère libre 4] varchar(255) NULL, 
	[Critère libre 5] varchar(255) NULL, 
	[Critère libre 6] varchar(255) NULL, 
	[Critère libre 7] varchar(255) NULL, 
	[Critère libre 8] varchar(255) NULL, 
	[Critère libre 9] varchar(255) NULL, 
	[Critère libre 10] varchar(255) NULL, 
	[Critère libre 11] varchar(255) NULL, 
	[Critère libre 12] varchar(255) NULL, 
	[Critère libre 13] varchar(255) NULL, 
	[Critère libre 14] varchar(255) NULL, 
	[Critère libre 15] varchar(255) NULL, 
	[Critère libre 16] varchar(255) NULL, 
	[Critère libre 17] varchar(255) NULL, 
	[IdClient] varchar(255) NOT NULL
);