CREATE TABLE [dbo].[Commande fournisseur ligne] (

	[Code commande] varchar(255) NULL, 
	[IdEntreprise] varchar(255) NOT NULL, 
	[Numéro ligne commande] float NULL, 
	[IdFournisseur] varchar(255) NOT NULL, 
	[IdSalariéAcheteur] varchar(255) NULL, 
	[IdActivité] varchar(255) NOT NULL, 
	[IdSecteuractivité] varchar(255) NOT NULL, 
	[Date création] date NULL, 
	[Date commande] date NULL, 
	[Délai livraison] date NULL, 
	[Date livraison] date NULL, 
	[Ecart date livraison] int NULL, 
	[Est dans délai] varchar(255) NULL, 
	[Est soldée] varchar(255) NULL, 
	[IdArticle] varchar(255) NOT NULL, 
	[IdPostegestion] varchar(255) NOT NULL, 
	[Repère 2] varchar(255) NULL, 
	[Repère plan] varchar(255) NULL, 
	[Indice] varchar(255) NULL, 
	[Zone 1] varchar(255) NULL, 
	[Zone 2] varchar(255) NULL, 
	[Quantité commandée] float NULL, 
	[Quantité à recevoir] float NULL, 
	[Unité achat] varchar(255) NULL, 
	[Prix unitaire achat] float NULL, 
	[Unité exploitation] varchar(255) NULL, 
	[Prix unitaire exploitation] float NULL, 
	[Montant achat] float NULL, 
	[Poids] float NULL, 
	[Volume] float NULL, 
	[Titre commande] varchar(255) NULL
);