CREATE TABLE [dbo].[Commande client analyse] (

	[Code commande] varchar(255) NULL, 
	[IdEntreprise] varchar(255) NOT NULL, 
	[Titre commande] varchar(255) NULL, 
	[Date commande] date NULL, 
	[IdClient] varchar(255) NOT NULL, 
	[IdGroupeclient] varchar(255) NOT NULL, 
	[Code salarié responsable] varchar(255) NULL, 
	[Code salarié commercial] varchar(255) NULL, 
	[Code salarié technicien] varchar(255) NULL, 
	[IdAffaire] varchar(255) NOT NULL, 
	[IdActivité] varchar(255) NOT NULL, 
	[IdSecteuractivité] varchar(255) NOT NULL, 
	[Code état avancement] varchar(255) NULL, 
	[Est commande interne] bit NULL, 
	[Montant vente commande] float NULL, 
	[Tps prévu commande] float NULL, 
	[Coût mo prévu commande] float NULL, 
	[Coût mo * coef 1 prévu commande] float NULL, 
	[Coût achat prévu commande] float NULL, 
	[Coût achat * coef 1 prévu commande] float NULL, 
	[Montant vente devis] float NULL, 
	[Coût revient devis] float NULL, 
	[Temps devis] float NULL, 
	[Coût revient mo devis] float NULL, 
	[Coût revient mo * coef 1 devis] float NULL, 
	[Montant mo devis] float NULL, 
	[Coût revient achat devis] float NULL, 
	[Coût revient achat * coef 1 devis] float NULL, 
	[Montant achat devis] float NULL, 
	[Montant vente fabriqué] float NULL, 
	[Montant vente livré] float NULL, 
	[Montant vente livré non facturé] float NULL, 
	[Montant vente facturé] float NULL, 
	[Temps réalisé] float NULL, 
	[Coût mo réalisé] float NULL, 
	[Coût mo * coef 1 réalisé] float NULL, 
	[Coût achat réalisé] float NULL, 
	[Coût achat * coef 1 réalisé] float NULL, 
	[Coût achat engagé] float NULL, 
	[Coût achat * coef 1 engagé] float NULL, 
	[Coût frais réalisé] float NULL, 
	[Coût frais * coef 1 réalisé] float NULL
);