CREATE TABLE [dbo].[Commande client ligne] (

	[Code commande] varchar(255) NULL, 
	[IdEntreprise] varchar(255) NOT NULL, 
	[Numéro ligne commande] float NULL, 
	[IdClient] varchar(255) NOT NULL, 
	[IdGroupeclient] varchar(255) NOT NULL, 
	[IdSalariéResponsable] varchar(255) NULL, 
	[IdSalariéCommercial] varchar(255) NULL, 
	[IdSalariéTechnicien] varchar(255) NULL, 
	[IdAffaire] varchar(255) NOT NULL, 
	[IdActivité] varchar(255) NOT NULL, 
	[IdSecteuractivité] varchar(255) NOT NULL, 
	[Date création] date NULL, 
	[Date commande] date NULL, 
	[Délai livraison] date NULL, 
	[Date livraison] date NULL, 
	[Ecart date livraison] int NULL, 
	[Est dans délai] varchar(255) NULL, 
	[Est soldée] varchar(255) NULL, 
	[IdArticle] varchar(255) NOT NULL, 
	[IdPostegestion] varchar(255) NOT NULL, 
	[Repère 2] varchar(255) NULL, 
	[Repère plan] varchar(255) NULL, 
	[Indice] varchar(255) NULL, 
	[Zone 1] varchar(255) NULL, 
	[Zone 2] varchar(255) NULL, 
	[Unité vente] varchar(255) NULL, 
	[Quantité commandée] float NULL, 
	[Quantité reste à livrer] float NULL, 
	[Prix unitaire vente] float NULL, 
	[Montant vente] float NULL, 
	[Poids] float NULL, 
	[Volume] float NULL, 
	[IdCommandeClient] varchar(255) NULL, 
	[Titre commande] varchar(255) NULL, 
	[Référence commande client] varchar(255) NULL, 
	[Code état avancement] varchar(255) NULL, 
	[Etat avancement] varchar(255) NULL, 
	[Code situation] varchar(255) NULL, 
	[Situation] varchar(255) NULL, 
	[Est commande interne] varchar(255) NULL, 
	[Est livrée] varchar(255) NULL, 
	[IdDevis] varchar(255) NULL, 
	[Code devis] varchar(255) NULL, 
	[Code et titre commande] varchar(255) NULL
);