CREATE TABLE [dbo].[Devis client gestion] (

	[Code devis] varchar(255) NULL, 
	[IdEntreprise] varchar(255) NOT NULL, 
	[Coût revient AMB] decimal(18,2) NULL, 
	[Coût revient AMP] decimal(18,2) NULL, 
	[Coût revient BUF] decimal(18,2) NULL, 
	[Coût revient CHA] decimal(18,2) NULL, 
	[Coût revient CHT] decimal(18,2) NULL, 
	[Coût revient COF] decimal(18,2) NULL, 
	[Coût revient COM] decimal(18,2) NULL, 
	[Coût revient ELF] decimal(18,2) NULL, 
	[Coût revient EMF] decimal(18,2) NULL, 
	[Coût revient FIF] decimal(18,2) NULL, 
	[Coût revient EQU] decimal(18,2) NULL, 
	[Coût revient FMA] decimal(18,2) NULL, 
	[Coût revient FMC] decimal(18,2) NULL, 
	[Coût revient FMP] decimal(18,2) NULL, 
	[Coût revient FRF] decimal(18,2) NULL, 
	[Coût revient GLF] decimal(18,2) NULL, 
	[Coût revient MAF] decimal(18,2) NULL, 
	[Coût revient INT] decimal(18,2) NULL, 
	[Coût revient MAR] decimal(18,2) NULL, 
	[Coût revient MAT] decimal(18,2) NULL, 
	[Coût revient MEN] decimal(18,2) NULL, 
	[Coût revient MEM] decimal(18,2) NULL, 
	[Coût revient MET] decimal(18,2) NULL, 
	[Coût revient MIE] decimal(18,2) NULL, 
	[Coût revient MOC] decimal(18,2) NULL, 
	[Coût revient MP] decimal(18,2) NULL, 
	[Coût revient MOE] decimal(18,2) NULL, 
	[Coût revient OAM] decimal(18,2) NULL, 
	[Coût revient MOEM] decimal(18,2) NULL, 
	[Coût revient MOF] decimal(18,2) NULL, 
	[Coût revient OCF] decimal(18,2) NULL, 
	[Coût revient MOP] decimal(18,2) NULL, 
	[Coût revient ODF] decimal(18,2) NULL, 
	[Coût revient MOM] decimal(18,2) NULL, 
	[Coût revient MOU] decimal(18,2) NULL, 
	[Coût revient ODM] decimal(18,2) NULL, 
	[Coût revient MOV] decimal(18,2) NULL, 
	[Coût revient OEF] decimal(18,2) NULL, 
	[Coût revient OEM] decimal(18,2) NULL, 
	[Coût revient OUF] decimal(18,2) NULL, 
	[Coût revient OFF] decimal(18,2) NULL, 
	[Coût revient PAF] decimal(18,2) NULL, 
	[Coût revient OFM] decimal(18,2) NULL, 
	[Coût revient OME] decimal(18,2) NULL, 
	[Coût revient PRF] decimal(18,2) NULL, 
	[Coût revient OMF] decimal(18,2) NULL, 
	[Coût revient OMM] decimal(18,2) NULL, 
	[Coût revient OPM] decimal(18,2) NULL, 
	[Coût revient PVC] decimal(18,2) NULL, 
	[Coût revient QUF] decimal(18,2) NULL, 
	[Coût revient RES] decimal(18,2) NULL, 
	[Coût revient REV] decimal(18,2) NULL, 
	[Coût revient SER] decimal(18,2) NULL, 
	[Coût revient STF] decimal(18,2) NULL, 
	[Coût revient TRA] decimal(18,2) NULL, 
	[Coût revient VIS] decimal(18,2) NULL, 
	[Coût revient VMO] decimal(18,2) NULL, 
	[Coût revient VMP] decimal(18,2) NULL, 
	[Coût revient VPF] decimal(18,2) NULL, 
	[Coût revient * coef 1 AMB] decimal(18,2) NULL, 
	[Coût revient * coef 1 AMP] decimal(18,2) NULL, 
	[Coût revient * coef 1 BUF] decimal(18,2) NULL, 
	[Coût revient * coef 1 CHA] decimal(18,2) NULL, 
	[Coût revient * coef 1 CHT] decimal(18,2) NULL, 
	[Coût revient * coef 1 COF] decimal(18,2) NULL, 
	[Coût revient * coef 1 COM] decimal(18,2) NULL, 
	[Coût revient * coef 1 ELF] decimal(18,2) NULL, 
	[Coût revient * coef 1 EMF] decimal(18,2) NULL, 
	[Coût revient * coef 1 EQU] decimal(18,2) NULL, 
	[Coût revient * coef 1 FIF] decimal(18,2) NULL, 
	[Coût revient * coef 1 FRF] decimal(18,2) NULL, 
	[Coût revient * coef 1 GLF] decimal(18,2) NULL, 
	[Coût revient * coef 1 MAF] decimal(18,2) NULL, 
	[Coût revient * coef 1 MAR] decimal(18,2) NULL, 
	[Coût revient * coef 1 MAT] decimal(18,2) NULL, 
	[Coût revient * coef 1 MEN] decimal(18,2) NULL, 
	[Coût revient * coef 1 MOC] decimal(18,2) NULL, 
	[Coût revient * coef 1 MOE] decimal(18,2) NULL, 
	[Coût revient * coef 1 MOP] decimal(18,2) NULL, 
	[Coût revient * coef 1 MOU] decimal(18,2) NULL, 
	[Coût revient * coef 1 MOV] decimal(18,2) NULL, 
	[Coût revient * coef 1 OAM] decimal(18,2) NULL, 
	[Coût revient * coef 1 OCF] decimal(18,2) NULL, 
	[Coût revient * coef 1 ODF] decimal(18,2) NULL, 
	[Coût revient * coef 1 OEM] decimal(18,2) NULL, 
	[Coût revient * coef 1 OME] decimal(18,2) NULL, 
	[Coût revient * coef 1 OMF] decimal(18,2) NULL, 
	[Coût revient * coef 1 OPM] decimal(18,2) NULL, 
	[Coût revient * coef 1 OUF] decimal(18,2) NULL, 
	[Coût revient * coef 1 PAF] decimal(18,2) NULL, 
	[Coût revient * coef 1 PRF] decimal(18,2) NULL, 
	[Coût revient * coef 1 PRO] decimal(18,2) NULL, 
	[Coût revient * coef 1 QUF] decimal(18,2) NULL, 
	[Coût revient * coef 1 RES] decimal(18,2) NULL, 
	[Coût revient * coef 1 SER] decimal(18,2) NULL, 
	[Coût revient * coef 1 STF] decimal(18,2) NULL, 
	[Coût revient * coef 1 TRA] decimal(18,2) NULL, 
	[Coût revient * coef 1 VIS] decimal(18,2) NULL, 
	[Coût revient * coef 1 VMO] decimal(18,2) NULL, 
	[Coût revient * coef 1 VMP] decimal(18,2) NULL, 
	[Coût revient * coef 1 VPF] decimal(18,2) NULL, 
	[Montant AMB] decimal(18,2) NULL, 
	[Montant AMP] decimal(18,2) NULL, 
	[Montant BUF] decimal(18,2) NULL, 
	[Montant CHA] decimal(18,2) NULL, 
	[Montant CHT] decimal(18,2) NULL, 
	[Montant COF] decimal(18,2) NULL, 
	[Montant COM] decimal(18,2) NULL, 
	[Montant ELF] decimal(18,2) NULL, 
	[Montant EMF] decimal(18,2) NULL, 
	[Montant EQU] decimal(18,2) NULL, 
	[Montant FMA] decimal(18,2) NULL, 
	[Montant FIF] decimal(18,2) NULL, 
	[Montant FMC] decimal(18,2) NULL, 
	[Montant FMP] decimal(18,2) NULL, 
	[Montant FRF] decimal(18,2) NULL, 
	[Montant GLF] decimal(18,2) NULL, 
	[Montant MAF] decimal(18,2) NULL, 
	[Montant MAR] decimal(18,2) NULL, 
	[Montant MAT] decimal(18,2) NULL, 
	[Montant MEN] decimal(18,2) NULL, 
	[Montant MIE] decimal(18,2) NULL, 
	[Montant MOC] decimal(18,2) NULL, 
	[Montant MOE] decimal(18,2) NULL, 
	[Montant MOEM] decimal(18,2) NULL, 
	[Montant MOF] decimal(18,2) NULL, 
	[Montant MOP] decimal(18,2) NULL, 
	[Montant MOU] decimal(18,2) NULL, 
	[Montant MOV] decimal(18,2) NULL, 
	[Montant OAM] decimal(18,2) NULL, 
	[Montant OCF] decimal(18,2) NULL, 
	[Montant ODF] decimal(18,2) NULL, 
	[Montant OEM] decimal(18,2) NULL, 
	[Montant OME] decimal(18,2) NULL, 
	[Montant OMF] decimal(18,2) NULL, 
	[Montant OMM] decimal(18,2) NULL, 
	[Montant OPM] decimal(18,2) NULL, 
	[Montant OUF] decimal(18,2) NULL, 
	[Montant PAF] decimal(18,2) NULL, 
	[Montant PRF] decimal(18,2) NULL, 
	[Montant PRO] decimal(18,2) NULL, 
	[Montant PVC] decimal(18,2) NULL, 
	[Montant QUF] decimal(18,2) NULL, 
	[Montant RES] decimal(18,2) NULL, 
	[Montant REV] decimal(18,2) NULL, 
	[Montant SER] decimal(18,2) NULL, 
	[Montant STF] decimal(18,2) NULL, 
	[Montant TRA] decimal(18,2) NULL, 
	[Montant VMB] decimal(18,2) NULL, 
	[Montant VMO] decimal(18,2) NULL, 
	[Montant VMP] decimal(18,2) NULL, 
	[Montant VPF] decimal(18,2) NULL, 
	[Montant VIS] decimal(18,2) NULL, 
	[Quantité AMB] decimal(18,2) NULL, 
	[Quantité AMP] decimal(18,2) NULL, 
	[Quantité BUF] decimal(18,2) NULL, 
	[Quantité CHA] decimal(18,2) NULL, 
	[Quantité CHT] decimal(18,2) NULL, 
	[Quantité COF] decimal(18,2) NULL, 
	[Quantité COM] decimal(18,2) NULL, 
	[Quantité ELF] decimal(18,2) NULL, 
	[Quantité EMF] decimal(18,2) NULL, 
	[Quantité EQU] decimal(18,2) NULL, 
	[Quantité FMA] decimal(18,2) NULL, 
	[Quantité FIF] decimal(18,2) NULL, 
	[Quantité FMC] decimal(18,2) NULL, 
	[Quantité FMP] decimal(18,2) NULL, 
	[Quantité FRF] decimal(18,2) NULL, 
	[Quantité GLF] decimal(18,2) NULL, 
	[Quantité MAF] decimal(18,2) NULL, 
	[Quantité MAR] decimal(18,2) NULL, 
	[Quantité MAT] decimal(18,2) NULL, 
	[Quantité MEN] decimal(18,2) NULL, 
	[Quantité MIE] decimal(18,2) NULL, 
	[Quantité MOC] decimal(18,2) NULL, 
	[Quantité MOE] decimal(18,2) NULL, 
	[Quantité MOEM] decimal(18,2) NULL, 
	[Quantité MOF] decimal(18,2) NULL, 
	[Quantité MOP] decimal(18,2) NULL, 
	[Quantité MOU] decimal(18,2) NULL, 
	[Quantité MOV] decimal(18,2) NULL, 
	[Quantité OAM] decimal(18,2) NULL, 
	[Quantité OCF] decimal(18,2) NULL, 
	[Quantité ODF] decimal(18,2) NULL, 
	[Quantité OEM] decimal(18,2) NULL, 
	[Quantité OME] decimal(18,2) NULL, 
	[Quantité OMF] decimal(18,2) NULL, 
	[Quantité OMM] decimal(18,2) NULL, 
	[Quantité OPM] decimal(18,2) NULL, 
	[Quantité OUF] decimal(18,2) NULL, 
	[Quantité PAF] decimal(18,2) NULL, 
	[Quantité PRF] decimal(18,2) NULL, 
	[Quantité PRO] decimal(18,2) NULL, 
	[Quantité PVC] decimal(18,2) NULL, 
	[Quantité QUF] decimal(18,2) NULL, 
	[Quantité RES] decimal(18,2) NULL, 
	[Quantité REV] decimal(18,2) NULL, 
	[Quantité SER] decimal(18,2) NULL, 
	[Quantité STF] decimal(18,2) NULL, 
	[Quantité TRA] decimal(18,2) NULL, 
	[Quantité VMB] decimal(18,2) NULL, 
	[Quantité VMO] decimal(18,2) NULL, 
	[Quantité VMP] decimal(18,2) NULL, 
	[Quantité VPF] decimal(18,2) NULL, 
	[Quantité VIS] decimal(18,2) NULL
);