CREATE TABLE [dbo].[Devis client ligne] (

	[Code devis] varchar(255) NULL, 
	[IdEntreprise] varchar(255) NOT NULL, 
	[Chapitre 1] float NULL, 
	[Chapitre 2] float NULL, 
	[Chapitre 3] float NULL, 
	[Numéro ligne devis] float NULL, 
	[IdClient] varchar(255) NOT NULL, 
	[IdGroupeclient] varchar(255) NOT NULL, 
	[IdSalariéCommercial] varchar(255) NULL, 
	[IdSalariéTechnicien] varchar(255) NULL, 
	[IdAffaire] varchar(255) NOT NULL, 
	[IdActivité] varchar(255) NOT NULL, 
	[IdSecteuractivité] varchar(255) NOT NULL, 
	[Date création] date NULL, 
	[Date devis] date NULL, 
	[Date acceptation/refus] date NULL, 
	[Est accepté] varchar(255) NULL, 
	[Est refusé] varchar(255) NULL, 
	[Est devis référence] varchar(255) NULL, 
	[Etat] varchar(255) NULL, 
	[IdArticle] varchar(255) NOT NULL, 
	[IdPostegestion] varchar(255) NOT NULL, 
	[Repère 2] varchar(255) NULL, 
	[Repère Plan] varchar(255) NULL, 
	[Indice] varchar(255) NULL, 
	[Zone 1] varchar(255) NULL, 
	[Zone 2] varchar(255) NULL, 
	[Unité vente] varchar(255) NULL, 
	[Quantité devis] float NULL, 
	[Prix unitaire vente] float NULL, 
	[Montant vente] float NULL, 
	[Coût revient] float NULL, 
	[Coût revient achat] float NULL, 
	[Coût revient mo] float NULL, 
	[Coût revient * coef 1] float NULL, 
	[Temps] float NULL, 
	[Poids] float NULL, 
	[Volume] float NULL, 
	[IdDevis] varchar(255) NULL, 
	[Titre devis] varchar(255) NULL, 
	[Motif refus] varchar(255) NULL, 
	[IdCommandeClient] varchar(255) NULL
);