CREATE TABLE [dbo].[Facture fournisseur ligne] (

	[Code facture] varchar(255) NULL, 
	[IdEntreprise] varchar(255) NOT NULL, 
	[Numéro ligne facture] float NULL, 
	[IdFournisseur] varchar(255) NOT NULL, 
	[IdSalariéAcheteur] varchar(255) NULL, 
	[IdActivité] varchar(255) NULL, 
	[IdSecteuractivité] varchar(255) NOT NULL, 
	[Date création] date NULL, 
	[Date facture] date NULL, 
	[Date échéance] date NULL, 
	[Est comptabilisée] varchar(255) NULL, 
	[Est soldée] varchar(255) NULL, 
	[Etat] varchar(255) NULL, 
	[Est avoir] varchar(255) NULL, 
	[Type] varchar(255) NULL, 
	[Est validée] varchar(255) NULL, 
	[IdArticle] varchar(255) NOT NULL, 
	[IdPostegestion] varchar(255) NOT NULL, 
	[Repère 2] varchar(255) NULL, 
	[Repère plan] varchar(255) NULL, 
	[Indice] varchar(255) NULL, 
	[Zone 1] varchar(255) NULL, 
	[Zone 2] varchar(255) NULL, 
	[Quantité facturée] float NULL, 
	[Unité achat] varchar(255) NULL, 
	[Prix unitaire achat] float NULL, 
	[Unité explotation] varchar(255) NULL, 
	[Prix unitaire exploitation] float NULL, 
	[Montant achat] float NULL, 
	[Poids] float NULL, 
	[Volume] float NULL, 
	[Titre facture] varchar(255) NULL
);