CREATE TABLE [dbo].[Facture client ligne] (

	[Code facture] varchar(255) NULL, 
	[IdEntreprise] varchar(255) NOT NULL, 
	[Chapitre 1] float NULL, 
	[Chapitre 2] float NULL, 
	[Chapitre 3] float NULL, 
	[Numéro ligne facture] float NULL, 
	[IdClient] varchar(255) NOT NULL, 
	[IdGroupeclient] varchar(255) NOT NULL, 
	[IdSalariéCommercial] varchar(255) NULL, 
	[IdSalariéTechnicien] varchar(255) NULL, 
	[IdAffaire] varchar(255) NOT NULL, 
	[IdActivité] varchar(255) NOT NULL, 
	[IdSecteuractivité] varchar(255) NOT NULL, 
	[Date création] date NULL, 
	[Date facture] date NULL, 
	[Date échéance] date NULL, 
	[Est comptabilisée] varchar(255) NULL, 
	[Est soldée] varchar(255) NULL, 
	[Etat] varchar(255) NULL, 
	[Est acompte] varchar(255) NULL, 
	[Est avoir] varchar(255) NULL, 
	[Type] varchar(255) NULL, 
	[Est validée] varchar(255) NULL, 
	[Code commande client] varchar(255) NULL, 
	[Code BL client] varchar(255) NULL, 
	[IdArticle] varchar(255) NOT NULL, 
	[IdPostegestion] varchar(255) NOT NULL, 
	[Repère 2] varchar(255) NULL, 
	[Repère plan] varchar(255) NULL, 
	[Indice] varchar(255) NULL, 
	[Zone 1] varchar(255) NULL, 
	[Zone 2] varchar(255) NULL, 
	[Unité vente] varchar(255) NULL, 
	[Quantité facturée] float NULL, 
	[Prix unitaire vente] float NULL, 
	[Montant vente] float NULL, 
	[Poids] float NULL, 
	[Volume] float NULL, 
	[IdCommandeClient] varchar(255) NOT NULL, 
	[Titre facture] varchar(255) NULL, 
	[Tranche retard] varchar(255) NULL, 
	[Ordre Tranche retard] int NULL
);