CREATE TABLE [dbo].[Facture client] (

	[Code facture] varchar(255) NULL, 
	[IdEntreprise] varchar(255) NOT NULL, 
	[Titre facture] varchar(255) NULL, 
	[IdClient] varchar(255) NOT NULL, 
	[IdGroupeclient] varchar(255) NOT NULL, 
	[Code salarié commercial] varchar(255) NULL, 
	[Code salarié technicien] varchar(255) NULL, 
	[IdAffaire] varchar(255) NOT NULL, 
	[IdActivité] varchar(255) NOT NULL, 
	[IdSecteuractivité] varchar(255) NOT NULL, 
	[Date création] date NULL, 
	[Date facture] date NULL, 
	[Date échéance] date NULL, 
	[Est comptabilisée] bit NULL, 
	[Est soldée] bit NULL, 
	[Etat] varchar(255) NULL, 
	[Est acompte] bit NULL, 
	[Est avoir] bit NULL, 
	[Type] varchar(255) NULL, 
	[Est validée] bit NULL, 
	[Montant HT] float NULL, 
	[Montant TTC] float NULL, 
	[Poids] float NULL, 
	[Volume] float NULL, 
	[Référence commerciale 1] varchar(255) NULL, 
	[Référence commerciale 2] varchar(255) NULL, 
	[Référence commerciale 3] varchar(255) NULL, 
	[Référence commerciale 4] varchar(255) NULL, 
	[Référence commerciale 5] varchar(255) NULL, 
	[Référence commerciale 6] varchar(255) NULL, 
	[Référence commerciale 7] varchar(255) NULL, 
	[Référence commerciale 8] varchar(255) NULL, 
	[Référence commerciale 9] varchar(255) NULL, 
	[Référence commerciale 10] varchar(255) NULL, 
	[Référence commerciale 11] varchar(255) NULL, 
	[Référence commerciale 12] varchar(255) NULL, 
	[Référence commerciale 13] varchar(255) NULL, 
	[Référence commerciale 14] varchar(255) NULL, 
	[Référence commerciale 15] varchar(255) NULL, 
	[Référence commerciale 16] varchar(255) NULL, 
	[Référence commerciale 17] varchar(255) NULL, 
	[Référence commerciale 18] varchar(255) NULL
);