CREATE TABLE [dbo].[Matériel] (

	[Code matériel] varchar(255) NULL, 
	[Matériel] varchar(255) NULL, 
	[Descriptif] varchar(255) NULL, 
	[Localisation] varchar(255) NULL, 
	[Code client] varchar(255) NULL, 
	[Date création] date NULL, 
	[Date modification] date NULL, 
	[Numéro série] varchar(255) NULL, 
	[Type matériel] varchar(255) NULL, 
	[Code salarié technicien] varchar(255) NULL, 
	[Date début garantie] date NULL, 
	[Date fin garantie] date NULL, 
	[Est usage interne] varchar(255) NULL, 
	[Critère libre 1] varchar(255) NULL, 
	[Critère libre 2] varchar(255) NULL, 
	[Critère libre 3] varchar(255) NULL, 
	[Critère libre 4] varchar(255) NULL, 
	[Critère libre 5] varchar(255) NULL, 
	[Critère libre 6] varchar(255) NULL, 
	[Critère libre 7] varchar(255) NULL, 
	[Critère libre 8] varchar(255) NULL, 
	[Critère libre 9] varchar(255) NULL, 
	[Critère libre 10] varchar(255) NULL, 
	[Critère libre 11] varchar(255) NULL, 
	[Critère libre 12] varchar(255) NULL, 
	[Critère libre 13] varchar(255) NULL, 
	[Critère libre 14] varchar(255) NULL, 
	[Critère libre 15] varchar(255) NULL, 
	[Critère libre 16] varchar(255) NULL, 
	[Critère libre 17] varchar(255) NULL, 
	[Critère libre 18] varchar(255) NULL, 
	[IdMatériel] int NOT NULL
);