CREATE TABLE [dbo].[Responsable] (

	[Code salarié] varchar(255) NULL, 
	[Nom prénom salarié] varchar(255) NULL, 
	[Code entreprise] int NULL, 
	[Nom salarié] varchar(255) NULL, 
	[Prénom salarié] varchar(255) NULL, 
	[Matricule RH] varchar(255) NULL, 
	[Code salarié responsable] varchar(255) NULL, 
	[Code service] varchar(255) NULL, 
	[Service] varchar(255) NULL, 
	[Code qualification] varchar(255) NULL, 
	[Qualification] varchar(255) NULL, 
	[Date création] date NULL, 
	[Date modification] date NULL, 
	[Date embauche] date NULL, 
	[Code fournisseur intérimaire] varchar(255) NULL, 
	[Est intérimaire] varchar(255) NULL, 
	[Est actif] varchar(255) NULL, 
	[Critère libre 1] varchar(255) NULL, 
	[Critère libre 2] varchar(255) NULL, 
	[Critère libre 3] varchar(255) NULL, 
	[Critère libre 4] varchar(255) NULL, 
	[Critère libre 5] varchar(255) NULL, 
	[Critère libre 6] varchar(255) NULL, 
	[Critère libre 7] varchar(255) NULL, 
	[Critère libre 8] varchar(255) NULL, 
	[Critère libre 9] varchar(255) NULL, 
	[Critère libre 10] varchar(255) NULL, 
	[Critère libre 11] varchar(255) NULL, 
	[Critère libre 12] varchar(255) NULL, 
	[Critère libre 13] varchar(255) NULL, 
	[Critère libre 14] varchar(255) NULL, 
	[Critère libre 15] varchar(255) NULL, 
	[Critère libre 16] varchar(255) NULL, 
	[Critère libre 17] varchar(255) NULL, 
	[Critère libre 18] varchar(255) NULL, 
	[IdResponsable] varchar(255) NOT NULL
);